apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: todo-app

commonLabels:
  environment: development

patches:
- target:
    kind: Deployment
    name: todo-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/todo-app:dev 